#include <bits/stdc++.h>
using namespace std;
using ll = long long;
#define el '\n'
#define vi vector<int>

int n, x, k;

int main(){
    ios::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);

    cin>>n>>x>>k;
    vector<int> a(n);
    for(int i = 0; i < n; i++) cin>>a[i];

    priority_queue<int, vi> maxx;
    priority_queue<int, vi, greater<int>> minn;

    for(int i = 0;i < n; i++){
        
    }

    return 0;
}